import os

AZURE_ACCOUNT_URL = os.getenv("AZURE_ACCOUNT_URL")
AZURE_CONTAINER_NAME = os.getenv("AZURE_CONTAINER_NAME")

CHECKPOINT_NAME = os.getenv("CHECKPOINT_NAME", "checkpoint.json")

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_KEY = os.getenv("AZURE_OPENAI_KEY")

TWITTER_CONSUMER_KEY = os.getenv("TWITTER_CONSUMER_KEY")
TWITTER_CONSUMER_SECRET = os.getenv("TWITTER_CONSUMER_SECRET")
TWITTER_TOKEN = os.getenv("TWITTER_TOKEN")
TWITTER_TOKEN_SECRET = os.getenv("TWITTER_TOKEN_SECRET")

POLL_DURATION_MINUTES = os.getenv("POLL_DURATION_MINUTES", 120)
